version: "3"

services:
  #My Sql
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: sazanami
      MYSQL_PASSWORD: sazanami
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    # MySQL設定ファイル
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    # MySQL起動時の初期化スクリプト置き場(*.sql、*.shのファイルを使えます)
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306